
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "leftADDSUBleftMULDIVrightPOWADD AND BOOL CHARACTER CONTINUE DCOLON DIV DO ELSE END ENDIF EQ EQEQ FLOAT GE GOTO GT IDEN IF INT INTEGER LE LEN LOGICAL LT MUL NE NOT OR POW PRINT PROGRAM READ REAL STRING SUB THENprogram : statementsstatements : statements statementstatements : statementstatement : IDEN EQ expr\nexpr : expr ADD expr\n     | expr SUB expr\n     | expr MUL expr\n     | expr DIV expr\n     | expr POW expr\nexpr : INTexpr : FLOATexpr : STRINGexpr : IDENexpr : '(' expr ')'"
    
_lr_action_items = {'IDEN':([0,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,],[4,4,-3,-2,7,-13,-4,-10,-11,-12,7,7,7,7,7,7,-5,-6,-7,-8,-9,-14,]),'$end':([1,2,3,5,7,8,9,10,11,19,20,21,22,23,24,],[0,-1,-3,-2,-13,-4,-10,-11,-12,-5,-6,-7,-8,-9,-14,]),'EQ':([4,],[6,]),'INT':([6,12,13,14,15,16,17,],[9,9,9,9,9,9,9,]),'FLOAT':([6,12,13,14,15,16,17,],[10,10,10,10,10,10,10,]),'STRING':([6,12,13,14,15,16,17,],[11,11,11,11,11,11,11,]),'(':([6,12,13,14,15,16,17,],[12,12,12,12,12,12,12,]),'ADD':([7,8,9,10,11,18,19,20,21,22,23,24,],[-13,13,-10,-11,-12,13,-5,-6,-7,-8,-9,-14,]),'SUB':([7,8,9,10,11,18,19,20,21,22,23,24,],[-13,14,-10,-11,-12,14,-5,-6,-7,-8,-9,-14,]),'MUL':([7,8,9,10,11,18,19,20,21,22,23,24,],[-13,15,-10,-11,-12,15,15,15,-7,-8,-9,-14,]),'DIV':([7,8,9,10,11,18,19,20,21,22,23,24,],[-13,16,-10,-11,-12,16,16,16,-7,-8,-9,-14,]),'POW':([7,8,9,10,11,18,19,20,21,22,23,24,],[-13,17,-10,-11,-12,17,17,17,17,17,17,-14,]),')':([7,9,10,11,18,19,20,21,22,23,24,],[-13,-10,-11,-12,24,-5,-6,-7,-8,-9,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,5,]),'expr':([6,12,13,14,15,16,17,],[8,18,19,20,21,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser.py',5),
  ('statements -> statements statement','statements',2,'p_statements_many','parser.py',9),
  ('statements -> statement','statements',1,'p_statements_one','parser.py',13),
  ('statement -> IDEN EQ expr','statement',3,'p_statement_assign','parser.py',17),
  ('expr -> expr ADD expr','expr',3,'p_expr_binop','parser.py',22),
  ('expr -> expr SUB expr','expr',3,'p_expr_binop','parser.py',23),
  ('expr -> expr MUL expr','expr',3,'p_expr_binop','parser.py',24),
  ('expr -> expr DIV expr','expr',3,'p_expr_binop','parser.py',25),
  ('expr -> expr POW expr','expr',3,'p_expr_binop','parser.py',26),
  ('expr -> INT','expr',1,'p_expr_int','parser.py',31),
  ('expr -> FLOAT','expr',1,'p_expr_float','parser.py',35),
  ('expr -> STRING','expr',1,'p_expr_string','parser.py',39),
  ('expr -> IDEN','expr',1,'p_expr_id','parser.py',43),
  ('expr -> ( expr )','expr',3,'p_expr_group','parser.py',47),
]
